### ISSUE TITLE
Can't start server

### ISSUE THREAD

**Issue by jcpsantiago** [joy-framework/joy#75]
I'm new to Janet and to `joy`.
I don't know what is triggering this error. I started a new project with `joy new proj` and everything was working i.e. server started with both `joy server|watch`.

Now I'm getting this even on a brand new project:
```
Server listening on [localhost:9001] ...
error: failed to intialize server

  in halo/start-server
  in server [halo_lib.janet] (tailcall) on line 6, column 3
  in _thunk [main.janet] on line -1, column -1
  in cli-main [boot.janet] on line 2853, column 35
```

I'm on MacOS, using the fish shell and running Janet 1.11.3. Installed `joy` via `jpm install joy` and added to my path wit `set PATH $PATH /usr/local/Cellar/janet/1.11.3/bin` (I use homebrew)

Didn't udpate anything, just closed my terminal and opened again.

**Comment by jcpsantiago** [comment]
rebooting my system fixed this 🤷  still don't know what caused it, but I'm closing the issue

**Comment by swlkr** [comment]
Hey, was out for a long weekend.

That's interesting, I'll have to look into how the ports are closed on SIGINT or maybe there's another signal I need to catch in halo. It was probably because the port was left open when it shouldn't be.

I'll write up a test for it and come up with a better error than "failed to initialize server" 😆
